name: AdvancedScoreboard
main: varion\AdvancedScoreboard
author: Varion
version: 1.5
api: 4.0.0

commands:
  as:
    usage: "/as"
    description: AdvancedScoreboard settings
    permission: advancedscoreboard.use
    permission-message: "You don't have permission to use this command."

permissions:
  advancedscoreboard.use:
    description: "Open AdvancedScoreboards menu"
    default: true  